
services:

  mysql:
    image: mysql
    container_name: mysql_product_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product-api
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql